import type { BoardSlotDefinition, BoardSide } from './boardTypes';

function characterSlots(side: BoardSide, y: number, startX: number): BoardSlotDefinition[] {
  return Array.from({ length: 5 }, (_, index) => ({
    id: `${side}-character-${index + 1}`,
    side,
    kind: 'character',
    label: `Character ${index + 1}`,
    x: startX + index * 8.35,
    y,
    width: 7.3,
    height: 18.2,
  }));
}

export const boardSlots: BoardSlotDefinition[] = [
  {
    id: 'opponent-hand',
    side: 'opponent',
    kind: 'hand',
    label: 'Hand',
    x: 18.8,
    y: 1.7,
    width: 19.4,
    height: 6.3,
  },
  {
    id: 'opponent-leader',
    side: 'opponent',
    kind: 'leader',
    label: 'Leader',
    x: 45.1,
    y: 2.6,
    width: 9.4,
    height: 17.8,
  },
  {
    id: 'opponent-life',
    side: 'opponent',
    kind: 'life',
    label: 'Life',
    x: 62.2,
    y: 7.4,
    width: 8.4,
    height: 8.4,
  },
  {
    id: 'opponent-don-area',
    side: 'opponent',
    kind: 'donArea',
    label: 'DON Area',
    x: 71.4,
    y: 8.8,
    width: 9.2,
    height: 8.8,
  },
  {
    id: 'opponent-don-deck',
    side: 'opponent',
    kind: 'donDeck',
    label: 'DON Deck',
    x: 73.6,
    y: 20.1,
    width: 6.1,
    height: 11.9,
  },
  {
    id: 'opponent-deck',
    side: 'opponent',
    kind: 'deck',
    label: 'Deck',
    x: 81.2,
    y: 22.7,
    width: 7.4,
    height: 16.8,
  },
  {
    id: 'opponent-trash',
    side: 'opponent',
    kind: 'trash',
    label: 'Trash',
    x: 82.2,
    y: 41.1,
    width: 6.3,
    height: 7.8,
  },
  ...characterSlots('opponent', 29.4, 29.4),
  {
    id: 'player-trash',
    side: 'player',
    kind: 'trash',
    label: 'Trash',
    x: 82.2,
    y: 57.6,
    width: 6.3,
    height: 7.8,
  },
  {
    id: 'player-deck',
    side: 'player',
    kind: 'deck',
    label: 'Deck',
    x: 81.7,
    y: 64.8,
    width: 7.4,
    height: 16.8,
  },
  {
    id: 'player-don-deck',
    side: 'player',
    kind: 'donDeck',
    label: 'DON Deck',
    x: 73.3,
    y: 66.5,
    width: 6.1,
    height: 11.9,
  },
  ...characterSlots('player', 61.1, 28.5),
  {
    id: 'player-don-area',
    side: 'player',
    kind: 'donArea',
    label: 'DON Area',
    x: 71.1,
    y: 78.2,
    width: 9.4,
    height: 8.8,
  },
  {
    id: 'player-leader',
    side: 'player',
    kind: 'leader',
    label: 'Leader',
    x: 45.1,
    y: 78.1,
    width: 9.4,
    height: 17.8,
  },
  {
    id: 'player-life',
    side: 'player',
    kind: 'life',
    label: 'Life',
    x: 62.2,
    y: 82,
    width: 8.4,
    height: 8.4,
  },
  {
    id: 'player-hand',
    side: 'player',
    kind: 'hand',
    label: 'Hand',
    x: 18.8,
    y: 91.8,
    width: 19.4,
    height: 6.3,
  },
];
