import type { BoardSlotDefinition, BoardSide } from './boardTypes';

const characterXs = [29.45, 37.9, 46.85, 55.65, 64.6];

function characterSlots(side: BoardSide, y: number): BoardSlotDefinition[] {
  return Array.from({ length: 5 }, (_, index) => ({
    id: `${side}-character-${index + 1}`,
    side,
    kind: 'character',
    label: `Character ${index + 1}`,
    x: characterXs[index],
    y,
    width: 7.1,
    height: 15.9,
  }));
}

export const boardSlots: BoardSlotDefinition[] = [
  {
    id: 'opponent-hand',
    side: 'opponent',
    kind: 'hand',
    label: 'Hand',
    x: 11.6,
    y: 15.4,
    width: 9.9,
    height: 5.4,
  },
  {
    id: 'opponent-leader',
    side: 'opponent',
    kind: 'leader',
    label: 'Leader',
    x: 51.9,
    y: 7.8,
    width: 7.2,
    height: 14,
  },
  {
    id: 'opponent-stage',
    side: 'opponent',
    kind: 'stage',
    label: 'Stage',
    x: 59.6,
    y: 7.8,
    width: 4.1,
    height: 14,
  },
  {
    id: 'opponent-life',
    side: 'opponent',
    kind: 'life',
    label: 'Life',
    x: 11.2,
    y: 21.4,
    width: 10.3,
    height: 22.1,
  },
  {
    id: 'opponent-don-area',
    side: 'opponent',
    kind: 'donArea',
    label: 'DON Area',
    x: 30.6,
    y: 7.8,
    width: 20.9,
    height: 14.2,
  },
  {
    id: 'opponent-don-deck',
    side: 'opponent',
    kind: 'donDeck',
    label: 'DON Deck',
    x: 64.1,
    y: 7.7,
    width: 5.6,
    height: 14.2,
  },
  {
    id: 'opponent-deck',
    side: 'opponent',
    kind: 'deck',
    label: 'Deck',
    x: 81.0,
    y: 20.6,
    width: 8.3,
    height: 18.4,
  },
  {
    id: 'opponent-trash',
    side: 'opponent',
    kind: 'trash',
    label: 'Trash',
    x: 82.2,
    y: 40.4,
    width: 6.9,
    height: 7.8,
  },
  ...characterSlots('opponent', 24.5),
  {
    id: 'player-trash',
    side: 'player',
    kind: 'trash',
    label: 'Trash',
    x: 82.8,
    y: 74.7,
    width: 7.2,
    height: 15.4,
  },
  {
    id: 'player-deck',
    side: 'player',
    kind: 'deck',
    label: 'Deck',
    x: 81.9,
    y: 51.8,
    width: 7.6,
    height: 19.8,
  },
  {
    id: 'player-don-deck',
    side: 'player',
    kind: 'donDeck',
    label: 'DON Deck',
    x: 65.5,
    y: 73.4,
    width: 5.8,
    height: 14.6,
  },
  ...characterSlots('player', 53.7),
  {
    id: 'player-don-area',
    side: 'player',
    kind: 'donArea',
    label: 'DON Area',
    x: 28.8,
    y: 72.9,
    width: 35.6,
    height: 10.5,
  },
  {
    id: 'player-leader',
    side: 'player',
    kind: 'leader',
    label: 'Leader',
    x: 43.2,
    y: 83.4,
    width: 7.4,
    height: 15,
  },
  {
    id: 'player-stage',
    side: 'player',
    kind: 'stage',
    label: 'Stage',
    x: 52.5,
    y: 85.2,
    width: 4.8,
    height: 13.3,
  },
  {
    id: 'player-life',
    side: 'player',
    kind: 'life',
    label: 'Life',
    x: 10.9,
    y: 49.8,
    width: 10.5,
    height: 28.4,
  },
  {
    id: 'player-hand',
    side: 'player',
    kind: 'hand',
    label: 'Hand',
    x: 11.3,
    y: 78.8,
    width: 9.9,
    height: 5.8,
  },
];
