name: Deploy to Droplet

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/dano/OneSake
            git pull origin main

            # BACKEND

            cd backend
            dotnet publish -c Release
            sudo systemctl restart onesake-backend

            # FRONTEND

            cd /home/dano/OneSake/frontend/web
            npm install
            npm run build

            sudo rm -rf /var/www/html/*
            sudo cp -r dist/* /var/www/html/

            sudo systemctl reload nginx
            
